// ============================================================
// Ubuntu Bootstrap Generator — 3-step wizard
// Step 1: Configuration  →  Step 2: Review & Confirm  →  Step 3: Download
// ============================================================

// ── Script Generation ────────────────────────────────────────

function esc(s) {
  return String(s ?? '').replace(/[$`"\\]/g, '\\$&')
}

function generateScript(cfg) {
  const L = []
  const add = (...lines) => L.push(...lines)
  const sec = (t) => add('', `# ── ${t} ${'─'.repeat(Math.max(0, 54 - t.length))}`)

  add('#!/bin/bash')
  add('set -e')
  add('export DEBIAN_FRONTEND=noninteractive')
  add('')
  add('# ============================================================')
  add('# Ubuntu Bootstrap Script')
  add('# Generated by AdminToolbox Bootstrap Generator')
  add(`# Generated: ${new Date().toUTCString()}`)
  add('# ============================================================')
  add('')

  if (cfg.logging) {
    sec('Logging')
    add('mkdir -p /var/log')
    add('exec > >(tee -a /var/log/bootstrap.log) 2>&1')
    add('echo "[bootstrap] Script started: $(date)"')
  }

  sec('Preflight checks')
  add('if [ "$(id -u)" -ne 0 ]; then')
  add('  echo "ERROR: This script must be run as root." >&2')
  add('  exit 1')
  add('fi')
  add('echo "[bootstrap] OS: $(. /etc/os-release && echo \\"$PRETTY_NAME\\")"')

  sec('System update')
  add('echo "[bootstrap] Updating system packages..."')
  add('apt-get update -qq')
  add('apt-get upgrade -y -qq')

  if (cfg.hostname) {
    sec('Hostname')
    add(`echo "[bootstrap] Setting hostname: ${esc(cfg.hostname)}"`)
    add(`hostnamectl set-hostname "${esc(cfg.hostname)}"`)
    add(`echo "${esc(cfg.hostname)}" > /etc/hostname`)
    add(`# Ensure /etc/hosts entry`)
    add(`if ! grep -qw "${esc(cfg.hostname)}" /etc/hosts; then`)
    add(`  sed -i "1a\\\\127.0.1.1 ${esc(cfg.hostname)}" /etc/hosts`)
    add('fi')
  }

  if (cfg.timezone && cfg.timezone !== 'UTC') {
    sec('Timezone')
    add(`echo "[bootstrap] Setting timezone: ${esc(cfg.timezone)}"`)
    add(`timedatectl set-timezone "${esc(cfg.timezone)}"`)
  }

  if (cfg.locale && cfg.locale !== 'en_US.UTF-8') {
    sec('Locale')
    add(`echo "[bootstrap] Setting locale: ${esc(cfg.locale)}"`)
    add('apt-get install -y -qq locales')
    add(`locale-gen "${esc(cfg.locale)}"`)
    add(`update-locale LANG="${esc(cfg.locale)}"`)
  }

  if (cfg.keyboard && cfg.keyboard !== 'us') {
    sec('Keyboard layout')
    add(`echo "[bootstrap] Setting keyboard: ${esc(cfg.keyboard)}"`)
    add(`cat > /etc/default/keyboard << 'KBEOF'`)
    add(`XKBMODEL="pc105"`)
    add(`XKBLAYOUT="${esc(cfg.keyboard)}"`)
    add(`XKBVARIANT=""`)
    add(`XKBOPTIONS=""`)
    add('KBEOF')
    add(`dpkg-reconfigure -f noninteractive keyboard-configuration 2>/dev/null || true`)
  }

  if (cfg.ntp) {
    sec('NTP / Time synchronization')
    add('echo "[bootstrap] Enabling NTP..."')
    add('timedatectl set-ntp true')
    if (cfg.ntpServer) {
      add(`echo "[bootstrap] Setting custom NTP server: ${esc(cfg.ntpServer)}"`)
      add('apt-get install -y -qq chrony')
      add(`sed -i '/^pool /d; /^server /d' /etc/chrony/chrony.conf 2>/dev/null || true`)
      add(`echo "server ${esc(cfg.ntpServer)} iburst" >> /etc/chrony/chrony.conf`)
      add('systemctl enable --now chrony')
    }
  }

  const pkgs = cfg.packages.filter(Boolean)
  if (pkgs.length > 0) {
    sec('Package installation')
    add(`echo "[bootstrap] Installing packages..."`)
    add(`apt-get install -y -qq \\`)
    pkgs.forEach((p, i) => add(`  ${p}${i < pkgs.length - 1 ? ' \\' : ''}`))
  }

  if (cfg.dns) {
    const servers = cfg.dns.trim().split(/[\s,]+/).filter(Boolean)
    if (servers.length > 0) {
      sec('DNS configuration')
      add('echo "[bootstrap] Setting DNS servers..."')
      add('mkdir -p /etc/systemd/resolved.conf.d')
      add(`cat > /etc/systemd/resolved.conf.d/custom-dns.conf << 'DNSEOF'`)
      add('[Resolve]')
      add(`DNS=${servers.join(' ')}`)
      add('DNSEOF')
      add('systemctl restart systemd-resolved 2>/dev/null || true')
    }
  }

  if (cfg.ufw) {
    sec('Firewall (UFW)')
    add('echo "[bootstrap] Configuring UFW..."')
    add('apt-get install -y -qq ufw')
    add('ufw --force reset')
    add('ufw default deny incoming')
    add('ufw default allow outgoing')
    const sshP = Number(cfg.sshPort) || 22
    add(`ufw allow ${sshP}/tcp   # SSH — always allowed`)
    for (const p of cfg.ufwPorts) {
      if (String(p) !== String(sshP)) add(`ufw allow ${p}/tcp`)
    }
    add('ufw --force enable')
    add('ufw status verbose')
  }

  sec('SSH configuration')
  add('echo "[bootstrap] Configuring SSH..."')
  add('CFG=/etc/ssh/sshd_config')
  const sshPort = Number(cfg.sshPort) || 22
  add(`sed -i "s/^#*\\s*Port .*/Port ${sshPort}/" "$CFG"`)
  add(`grep -qE "^Port " "$CFG" || echo "Port ${sshPort}" >> "$CFG"`)
  const rootVal = cfg.permitRootLogin ? 'yes' : 'no'
  add(`sed -i "s/^#*\\s*PermitRootLogin .*/PermitRootLogin ${rootVal}/" "$CFG"`)
  add(`grep -qE "^PermitRootLogin " "$CFG" || echo "PermitRootLogin ${rootVal}" >> "$CFG"`)
  const pwVal = cfg.passwordAuth ? 'yes' : 'no'
  add(`sed -i "s/^#*\\s*PasswordAuthentication .*/PasswordAuthentication ${pwVal}/" "$CFG"`)
  add(`grep -qE "^PasswordAuthentication " "$CFG" || echo "PasswordAuthentication ${pwVal}" >> "$CFG"`)
  add('systemctl restart sshd 2>/dev/null || systemctl restart ssh 2>/dev/null || true')

  const hasCleanup = cfg.removeSnap || cfg.disableCloudInit || cfg.removeServices || cfg.aptClean
  if (hasCleanup) {
    sec('Cleanup / Debloat')

    if (cfg.removeSnap) {
      add('echo "[bootstrap] Removing snapd..."')
      add('systemctl stop snapd.service snapd.socket 2>/dev/null || true')
      add('apt-get purge -y snapd 2>/dev/null || true')
      add('apt-mark hold snapd 2>/dev/null || true')
      add('rm -rf /snap /var/snap /var/lib/snapd /var/cache/snapd /usr/lib/snapd 2>/dev/null || true')
    }

    if (cfg.disableCloudInit) {
      add('echo "[bootstrap] Disabling cloud-init..."')
      add('touch /etc/cloud/cloud-init.disabled')
      add('for svc in cloud-init cloud-init-local cloud-config cloud-final; do')
      add('  systemctl disable "$svc" 2>/dev/null || true')
      add('  systemctl stop    "$svc" 2>/dev/null || true')
      add('done')
    }

    if (cfg.removeServices) {
      add('echo "[bootstrap] Removing unnecessary services..."')
      add('for pkg in whoopsie apport popularity-contest ubuntu-report; do')
      add('  dpkg -s "$pkg" &>/dev/null 2>&1 && apt-get purge -y "$pkg" || true')
      add('done')
    }

    if (cfg.aptClean) {
      add('echo "[bootstrap] Running apt cleanup..."')
      add('apt-get autoremove -y -qq')
      add('apt-get clean')
    }
  }

  sec('Done')
  add('echo ""')
  add('echo "════════════════════════════════════════════════════"')
  add('echo " Bootstrap completed successfully: $(date)"')
  if (cfg.logging) add('echo " Full log: /var/log/bootstrap.log"')
  add('echo "════════════════════════════════════════════════════"')

  return L.join('\n') + '\n'
}

// ── Review HTML ───────────────────────────────────────────────

function badge(val, trueLabel = 'Aktiviert', falseLabel = 'Deaktiviert') {
  const ok = Boolean(val)
  return `<span class="bg-badge ${ok ? 'bg-badge-ok' : 'bg-badge-off'}">${ok ? trueLabel : falseLabel}</span>`
}

function reviewRow(label, value) {
  return `<div class="bg-rev-row"><span class="bg-rev-label">${label}</span><span class="bg-rev-val">${value}</span></div>`
}

function buildReview(cfg) {
  const pkgs = cfg.packages.filter(Boolean)

  return `
  <div class="bg-rev-section">
    <div class="bg-rev-head">System</div>
    ${reviewRow('Hostname', cfg.hostname || '<em>nicht gesetzt</em>')}
    ${reviewRow('Zeitzone', cfg.timezone || 'UTC')}
    ${reviewRow('Locale', cfg.locale || 'en_US.UTF-8')}
    ${reviewRow('Tastaturlayout', cfg.keyboard || 'us')}
    ${reviewRow('Logging', badge(cfg.logging, '/var/log/bootstrap.log', 'Deaktiviert'))}
  </div>

  <div class="bg-rev-section">
    <div class="bg-rev-head">SSH & Sicherheit</div>
    ${reviewRow('SSH-Port', cfg.sshPort || 22)}
    ${reviewRow('Root-Login', badge(cfg.permitRootLogin, 'Erlaubt ⚠', 'Verboten'))}
    ${reviewRow('Passwort-Auth', badge(cfg.passwordAuth, 'Aktiviert ⚠', 'Deaktiviert'))}
  </div>

  <div class="bg-rev-section">
    <div class="bg-rev-head">Firewall (UFW)</div>
    ${reviewRow('UFW', badge(cfg.ufw, 'Aktiviert', 'Deaktiviert'))}
    ${cfg.ufw ? reviewRow('Erlaubte Ports', cfg.ufwPorts.length ? cfg.ufwPorts.map(p => `<span class="bg-port-badge">${p}</span>`).join(' ') + ` <span class="bg-port-badge bg-port-ssh">SSH:${cfg.sshPort||22}</span>` : '<em>nur SSH</em>') : ''}
  </div>

  <div class="bg-rev-section">
    <div class="bg-rev-head">NTP</div>
    ${reviewRow('NTP', badge(cfg.ntp))}
    ${cfg.ntp && cfg.ntpServer ? reviewRow('NTP-Server', cfg.ntpServer) : ''}
  </div>

  <div class="bg-rev-section">
    <div class="bg-rev-head">Pakete (${pkgs.length})</div>
    ${pkgs.length ? `<div class="bg-pkg-preview">${pkgs.map(p => `<span class="bg-port-badge">${p}</span>`).join(' ')}</div>` : reviewRow('', '<em>keine Pakete ausgewählt</em>')}
  </div>

  <div class="bg-rev-section">
    <div class="bg-rev-head">Bereinigung</div>
    ${reviewRow('snapd entfernen', badge(cfg.removeSnap))}
    ${reviewRow('cloud-init deaktivieren', badge(cfg.disableCloudInit))}
    ${reviewRow('Dienste entfernen', badge(cfg.removeServices))}
    ${reviewRow('apt autoremove & clean', badge(cfg.aptClean))}
  </div>

  <div class="bg-rev-section">
    <div class="bg-rev-head">Netzwerk / DNS</div>
    ${reviewRow('DNS-Server', cfg.dns || '<em>nicht gesetzt (System-Standard)</em>')}
  </div>`
}

function buildContextWarnings(cfg) {
  const warns = []

  if (cfg.permitRootLogin) {
    warns.push({ level: 'warn', text: 'Root-Login per SSH ist aktiviert. Dies ist unsicher und sollte nur in kontrollierten Umgebungen verwendet werden.' })
  }
  if (cfg.passwordAuth) {
    warns.push({ level: 'warn', text: 'Passwort-Authentifizierung ist aktiviert. Für höhere Sicherheit empfiehlt sich ausschließlich Key-basierte Authentifizierung.' })
  }
  if (cfg.sshPort && Number(cfg.sshPort) !== 22) {
    warns.push({ level: 'info', text: `SSH-Port ist auf ${cfg.sshPort} geändert. Stelle sicher, dass dieser Port in der Firewall erlaubt ist — sonst verlierst du den Zugang.` })
  }
  if (cfg.ufw && cfg.ufwPorts.length === 0) {
    warns.push({ level: 'warn', text: 'Firewall aktiviert, aber keine zusätzlichen Ports definiert. Nur der SSH-Port ist erreichbar.' })
  }
  if (cfg.removeSnap && cfg.packages.includes('snapd')) {
    warns.push({ level: 'info', text: 'snapd ist gleichzeitig als Paket ausgewählt und soll entfernt werden. Das Entfernen überschreibt die Installation.' })
  }

  if (!warns.length) return ''

  return `<div class="bg-ctx-warns">${warns.map(w =>
    `<div class="bg-ctx-warn bg-ctx-${w.level}">
      <span class="bg-ctx-icon">${w.level === 'warn' ? '⚠' : 'ℹ'}</span>
      <span>${w.text}</span>
    </div>`
  ).join('')}</div>`
}

// ── HTML Template ─────────────────────────────────────────────

const BASE_PKGS = ['curl','wget','git','vim','nano','htop','net-tools','dnsutils','unzip','ca-certificates']
const OPT_PKGS  = ['build-essential','jq','lsof','tcpdump']
const DEFAULT_BASE = new Set(['curl','wget','git','nano','htop','net-tools','dnsutils','unzip','ca-certificates'])

export function html() {
  return `
  <div class="tool-panel">
    <div class="tool-header">
      <h1 class="tool-title">Ubuntu Bootstrap Generator</h1>
      <p class="tool-subtitle">Bash-Einrichtungsskript für frische Ubuntu-Server konfigurieren, prüfen und herunterladen</p>
    </div>
    <div class="tool-body">

      <!-- ── Progress indicator ── -->
      <div class="bg-progress" aria-label="Schritte">
        <div class="bg-prog-step bg-prog-active" id="bg-prog-1"><span class="bg-prog-num">1</span> Konfiguration</div>
        <div class="bg-prog-arrow">›</div>
        <div class="bg-prog-step" id="bg-prog-2"><span class="bg-prog-num">2</span> Überprüfen</div>
        <div class="bg-prog-arrow">›</div>
        <div class="bg-prog-step" id="bg-prog-3"><span class="bg-prog-num">3</span> Herunterladen</div>
      </div>

      <!-- ═══════════════════════════════════════ STEP 1 ═══ -->
      <div id="bg-s1">

        <!-- System -->
        <div class="bg-section">
          <div class="bg-sec-title">System</div>
          <div class="form-grid">
            <div class="form-row">
              <label for="bg-hostname">Hostname <span class="admin-hint">(optional)</span></label>
              <input id="bg-hostname" class="input" type="text" placeholder="z.B. myserver" maxlength="63">
            </div>
            <div class="form-row">
              <label for="bg-timezone">Zeitzone</label>
              <select id="bg-timezone" class="select">
                <option value="UTC">UTC</option>
                <option value="Europe/Berlin">Europe/Berlin</option>
                <option value="Europe/London">Europe/London</option>
                <option value="Europe/Paris">Europe/Paris</option>
                <option value="Europe/Zurich">Europe/Zurich</option>
                <option value="Europe/Amsterdam">Europe/Amsterdam</option>
                <option value="America/New_York">America/New_York</option>
                <option value="America/Chicago">America/Chicago</option>
                <option value="America/Los_Angeles">America/Los_Angeles</option>
                <option value="Asia/Tokyo">Asia/Tokyo</option>
                <option value="Asia/Singapore">Asia/Singapore</option>
                <option value="Australia/Sydney">Australia/Sydney</option>
              </select>
            </div>
            <div class="form-row">
              <label for="bg-locale">Locale</label>
              <select id="bg-locale" class="select">
                <option value="en_US.UTF-8">en_US.UTF-8</option>
                <option value="en_GB.UTF-8">en_GB.UTF-8</option>
                <option value="de_DE.UTF-8">de_DE.UTF-8</option>
                <option value="de_CH.UTF-8">de_CH.UTF-8</option>
                <option value="fr_FR.UTF-8">fr_FR.UTF-8</option>
                <option value="es_ES.UTF-8">es_ES.UTF-8</option>
                <option value="it_IT.UTF-8">it_IT.UTF-8</option>
                <option value="nl_NL.UTF-8">nl_NL.UTF-8</option>
              </select>
            </div>
            <div class="form-row">
              <label for="bg-keyboard">Tastaturlayout</label>
              <select id="bg-keyboard" class="select">
                <option value="us">US (us)</option>
                <option value="de">Deutsch (de)</option>
                <option value="de-latin1">Deutsch Latin1 (de-latin1)</option>
                <option value="ch">Schweiz (ch)</option>
                <option value="gb">Britisch (gb)</option>
                <option value="fr">Französisch (fr)</option>
                <option value="es">Spanisch (es)</option>
                <option value="it">Italienisch (it)</option>
                <option value="nl">Niederländisch (nl)</option>
              </select>
            </div>
          </div>
          <div style="margin-top:12px">
            <label class="bg-chk-label"><input type="checkbox" id="bg-logging" checked> Ausgabe in <code>/var/log/bootstrap.log</code> schreiben</label>
          </div>
        </div>

        <div class="divider"></div>

        <!-- SSH -->
        <div class="bg-section">
          <div class="bg-sec-title">SSH & Zugangskonfiguration</div>
          <div class="form-grid">
            <div class="form-row">
              <label for="bg-ssh-port">SSH-Port</label>
              <input id="bg-ssh-port" class="input" type="number" min="1" max="65535" value="22" style="max-width:120px">
            </div>
            <div></div>
            <div class="form-row">
              <label class="bg-chk-label"><input type="checkbox" id="bg-root-login"> Root-Login per SSH erlauben</label>
            </div>
            <div class="form-row">
              <label class="bg-chk-label"><input type="checkbox" id="bg-pw-auth"> Passwort-Authentifizierung erlauben</label>
            </div>
          </div>
        </div>

        <div class="divider"></div>

        <!-- NTP -->
        <div class="bg-section">
          <div class="bg-sec-title">Zeitsynchronisation (NTP)</div>
          <label class="bg-chk-label" style="margin-bottom:10px"><input type="checkbox" id="bg-ntp" checked> NTP aktivieren</label>
          <div class="form-row">
            <label for="bg-ntp-server">Eigener NTP-Server <span class="admin-hint">(optional, z.B. pool.ntp.org)</span></label>
            <input id="bg-ntp-server" class="input" type="text" placeholder="pool.ntp.org" style="max-width:280px">
          </div>
        </div>

        <div class="divider"></div>

        <!-- Packages -->
        <div class="bg-section">
          <div class="bg-sec-title">Pakete</div>
          <div class="bg-pkg-group-title">Basis-Pakete</div>
          <div class="bg-pkg-grid">
            ${BASE_PKGS.map(p => `
              <label class="bg-chk-label">
                <input type="checkbox" class="bg-pkg-cb" value="${p}" ${DEFAULT_BASE.has(p) ? 'checked' : ''}> ${p}
              </label>`).join('')}
          </div>
          <div class="bg-pkg-group-title" style="margin-top:14px">Optionale Pakete</div>
          <div class="bg-pkg-grid">
            ${OPT_PKGS.map(p => `
              <label class="bg-chk-label">
                <input type="checkbox" class="bg-pkg-cb" value="${p}"> ${p}
              </label>`).join('')}
          </div>
        </div>

        <div class="divider"></div>

        <!-- Cleanup -->
        <div class="bg-section">
          <div class="bg-sec-title">Bereinigung / Debloat</div>
          <div class="bg-check-grid">
            <label class="bg-chk-label"><input type="checkbox" id="bg-rm-snap"> snapd entfernen</label>
            <label class="bg-chk-label"><input type="checkbox" id="bg-rm-cloud"> cloud-init deaktivieren</label>
            <label class="bg-chk-label"><input type="checkbox" id="bg-rm-svc"> Unnötige Dienste entfernen <span class="admin-hint">(whoopsie, apport …)</span></label>
            <label class="bg-chk-label"><input type="checkbox" id="bg-apt-clean" checked> apt autoremove &amp; clean ausführen</label>
          </div>
        </div>

        <div class="divider"></div>

        <!-- Firewall -->
        <div class="bg-section">
          <div class="bg-sec-title">Firewall (UFW)</div>
          <label class="bg-chk-label" style="margin-bottom:10px">
            <input type="checkbox" id="bg-ufw"> UFW-Firewall aktivieren
          </label>
          <div id="bg-ufw-opts" hidden>
            <div class="form-row">
              <label>Erlaubte Ports (TCP) — SSH wird automatisch hinzugefügt</label>
              <div class="bg-port-add-row">
                <input id="bg-port-input" class="input" type="text" placeholder="z.B. 80 443 8080" style="max-width:220px">
                <button class="btn btn-secondary btn-sm" id="bg-port-add-btn">+ Hinzufügen</button>
              </div>
              <div id="bg-port-tags" class="bg-port-tag-wrap"></div>
              <div class="input-error-msg" id="bg-port-err"></div>
            </div>
          </div>
        </div>

        <div class="divider"></div>

        <!-- DNS -->
        <div class="bg-section">
          <div class="bg-sec-title">Netzwerk / DNS</div>
          <div class="form-row">
            <label for="bg-dns">DNS-Server <span class="admin-hint">(optional — Leerzeichen oder Komma getrennt)</span></label>
            <input id="bg-dns" class="input" type="text" placeholder="1.1.1.1 8.8.8.8" style="max-width:300px">
          </div>
        </div>

        <div class="btn-row" style="margin-top:24px">
          <button class="btn btn-primary" id="bg-to-review">Weiter → Konfiguration prüfen</button>
        </div>

      </div><!-- /bg-s1 -->

      <!-- ═══════════════════════════════════════ STEP 2 ═══ -->
      <div id="bg-s2" hidden>

        <!-- Warning box -->
        <div class="bg-warn-box">
          <div class="bg-warn-icon">⚠</div>
          <div>
            <strong>Wichtiger Sicherheitshinweis</strong><br>
            Dieses Skript nimmt <strong>systemweite Änderungen</strong> an deinem Server vor — SSH-Konfiguration, Firewall-Regeln, Paketinstallation und mehr.
            Eine falsche Konfiguration kann zum <strong>Verlust des Serverzugangs</strong> oder zu Instabilität führen.
            Überprüfe alle Einstellungen sorgfältig.<br>
            <strong>Verwendung auf eigene Gefahr. Keine Garantie oder Haftung.</strong>
          </div>
        </div>

        <!-- Contextual warnings -->
        <div id="bg-ctx-warns"></div>

        <!-- Review summary -->
        <div class="bg-review-card">
          <div class="bg-review-card-title">Konfigurationsübersicht</div>
          <div id="bg-review-body"></div>
        </div>

        <!-- Confirmation -->
        <div class="bg-confirm-box">
          <label class="bg-confirm-label">
            <input type="checkbox" id="bg-confirm-1">
            Ich habe alle Konfigurationsoptionen geprüft und möchte das Skript generieren.
          </label>
          <label class="bg-confirm-label">
            <input type="checkbox" id="bg-confirm-2">
            Ich verstehe, dass dieses Skript systemweite Änderungen vornimmt, und verwende es auf eigene Gefahr.
          </label>
        </div>

        <div class="btn-row">
          <button class="btn btn-ghost" id="bg-back">← Zurück zur Konfiguration</button>
          <button class="btn btn-primary" id="bg-generate" disabled>Skript generieren &amp; herunterladen</button>
        </div>

      </div><!-- /bg-s2 -->

      <!-- ═══════════════════════════════════════ STEP 3 ═══ -->
      <div id="bg-s3" hidden>

        <div class="bg-success-bar">✓ Skript erfolgreich generiert</div>

        <!-- Direct download -->
        <div class="bg-dl-section">
          <div class="bg-dl-title">Direkter Download</div>
          <p class="bg-dl-desc">Das Skript direkt als Datei herunterladen und manuell prüfen bevor es ausgeführt wird.</p>
          <button class="btn btn-primary" id="bg-dl-btn">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
              <polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
            </svg>
            bootstrap.sh herunterladen
          </button>
        </div>

        <div class="divider"></div>

        <!-- Temp link -->
        <div class="bg-dl-section">
          <div class="bg-dl-title">Temporärer Download-Link <span class="admin-hint">(5 Minuten gültig)</span></div>
          <p class="bg-dl-desc">Einmal-Link zum direkten Ausführen auf dem Server via curl. Läuft nach 5 Minuten automatisch ab.</p>

          <div id="bg-tl-loading" class="bg-tl-loading">Link wird generiert…</div>

          <div id="bg-tl-result" hidden>
            <div class="bg-tl-row">
              <input id="bg-tl-url" class="input bg-mono-input" type="text" readonly>
              <button class="btn btn-secondary btn-sm" id="bg-tl-copy-url">Kopieren</button>
            </div>
            <div class="bg-tl-expires" id="bg-tl-expires"></div>
            <div class="bg-tl-cmd-wrap">
              <div class="bg-tl-cmd-label">Direkt ausführen (als root):</div>
              <div class="bg-tl-cmd-row">
                <code id="bg-tl-cmd" class="bg-tl-cmd"></code>
                <button class="btn btn-ghost btn-sm" id="bg-tl-copy-cmd">Kopieren</button>
              </div>
            </div>
          </div>

          <div id="bg-tl-err" class="input-error-msg"></div>
        </div>

        <div class="btn-row" style="margin-top:24px">
          <button class="btn btn-ghost" id="bg-restart">← Neue Konfiguration</button>
        </div>

      </div><!-- /bg-s3 -->

    </div>
  </div>`
}

// ── Init ──────────────────────────────────────────────────────

export function init(container) {
  // State
  const ports = []
  let generatedScript = ''

  // Elements
  const s1 = container.querySelector('#bg-s1')
  const s2 = container.querySelector('#bg-s2')
  const s3 = container.querySelector('#bg-s3')

  function showStep(n) {
    s1.hidden = n !== 1
    s2.hidden = n !== 2
    s3.hidden = n !== 3
    for (let i = 1; i <= 3; i++) {
      const el = container.querySelector(`#bg-prog-${i}`)
      el.classList.toggle('bg-prog-active', i === n)
      el.classList.toggle('bg-prog-done', i < n)
    }
  }

  // UFW toggle
  const ufwCb    = container.querySelector('#bg-ufw')
  const ufwOpts  = container.querySelector('#bg-ufw-opts')
  ufwCb.addEventListener('change', () => { ufwOpts.hidden = !ufwCb.checked })

  // Port management
  const portInput  = container.querySelector('#bg-port-input')
  const portAddBtn = container.querySelector('#bg-port-add-btn')
  const portTags   = container.querySelector('#bg-port-tags')
  const portErr    = container.querySelector('#bg-port-err')

  function renderPorts() {
    portTags.innerHTML = ports.map((p, i) => `
      <span class="bg-port-tag">
        ${p}
        <button class="bg-port-tag-rm" data-i="${i}" title="Entfernen">×</button>
      </span>`).join('')
    portTags.querySelectorAll('.bg-port-tag-rm').forEach(btn => {
      btn.addEventListener('click', () => { ports.splice(parseInt(btn.dataset.i), 1); renderPorts() })
    })
  }

  function addPorts() {
    portErr.textContent = ''
    const vals = portInput.value.trim().split(/[\s,]+/).filter(Boolean)
    if (!vals.length) return
    for (const v of vals) {
      const n = parseInt(v, 10)
      if (isNaN(n) || n < 1 || n > 65535) { portErr.textContent = `Ungültiger Port: "${v}"`; return }
      if (!ports.includes(n)) ports.push(n)
    }
    portInput.value = ''
    renderPorts()
  }

  portAddBtn.addEventListener('click', addPorts)
  portInput.addEventListener('keydown', e => { if (e.key === 'Enter') { e.preventDefault(); addPorts() } })

  // Read config from form
  function readConfig() {
    const sshPort = parseInt(container.querySelector('#bg-ssh-port').value) || 22
    return {
      hostname:       container.querySelector('#bg-hostname').value.trim(),
      timezone:       container.querySelector('#bg-timezone').value,
      locale:         container.querySelector('#bg-locale').value,
      keyboard:       container.querySelector('#bg-keyboard').value,
      logging:        container.querySelector('#bg-logging').checked,
      sshPort,
      permitRootLogin: container.querySelector('#bg-root-login').checked,
      passwordAuth:   container.querySelector('#bg-pw-auth').checked,
      ntp:            container.querySelector('#bg-ntp').checked,
      ntpServer:      container.querySelector('#bg-ntp-server').value.trim(),
      packages:       [...container.querySelectorAll('.bg-pkg-cb:checked')].map(el => el.value),
      removeSnap:     container.querySelector('#bg-rm-snap').checked,
      disableCloudInit: container.querySelector('#bg-rm-cloud').checked,
      removeServices: container.querySelector('#bg-rm-svc').checked,
      aptClean:       container.querySelector('#bg-apt-clean').checked,
      ufw:            container.querySelector('#bg-ufw').checked,
      ufwPorts:       [...ports],
      dns:            container.querySelector('#bg-dns').value.trim(),
    }
  }

  // Step 1 → Step 2
  container.querySelector('#bg-to-review').addEventListener('click', () => {
    const cfg = readConfig()

    container.querySelector('#bg-review-body').innerHTML    = buildReview(cfg)
    container.querySelector('#bg-ctx-warns').innerHTML      = buildContextWarnings(cfg)

    // Reset confirmations
    container.querySelector('#bg-confirm-1').checked = false
    container.querySelector('#bg-confirm-2').checked = false
    container.querySelector('#bg-generate').disabled  = true

    showStep(2)
    container.querySelector('#bg-s2').scrollIntoView({ behavior: 'smooth', block: 'start' })
  })

  // Confirm checkboxes enable/disable generate button
  const confirm1 = container.querySelector('#bg-confirm-1')
  const confirm2 = container.querySelector('#bg-confirm-2')
  const generateBtn = container.querySelector('#bg-generate')

  function updateGenerateBtn() {
    generateBtn.disabled = !(confirm1.checked && confirm2.checked)
  }
  confirm1.addEventListener('change', updateGenerateBtn)
  confirm2.addEventListener('change', updateGenerateBtn)

  // Back to step 1
  container.querySelector('#bg-back').addEventListener('click', () => showStep(1))

  // Step 2 → Step 3: generate script
  generateBtn.addEventListener('click', async () => {
    const cfg    = readConfig()
    generatedScript = generateScript(cfg)

    showStep(3)

    // Request temp link from backend
    const tlLoading = container.querySelector('#bg-tl-loading')
    const tlResult  = container.querySelector('#bg-tl-result')
    const tlErr     = container.querySelector('#bg-tl-err')
    tlLoading.hidden = false
    tlResult.hidden  = true
    tlErr.textContent = ''

    try {
      const res  = await fetch('/api/scriptstore', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ script: generatedScript })
      })
      const data = await res.json()

      if (!res.ok) { tlErr.textContent = data.error || 'Fehler beim Erstellen des Links.'; tlLoading.hidden = true; return }

      const url     = `${window.location.origin}/script/${data.token}.sh`
      const curlCmd = `bash <(curl -fsSL "${url}")`
      const expires = new Date(data.expires)

      container.querySelector('#bg-tl-url').value      = url
      container.querySelector('#bg-tl-cmd').textContent = curlCmd
      container.querySelector('#bg-tl-expires').textContent =
        `Link läuft ab um: ${expires.toLocaleTimeString('de-DE')} (in 5 Minuten)`

      tlLoading.hidden = true
      tlResult.hidden  = false
    } catch {
      tlErr.textContent = 'Backend nicht erreichbar. Direkter Download weiterhin verfügbar.'
      tlLoading.hidden = true
    }

    container.querySelector('#bg-s3').scrollIntoView({ behavior: 'smooth', block: 'start' })
  })

  // Direct download
  container.querySelector('#bg-dl-btn').addEventListener('click', () => {
    const blob = new Blob([generatedScript], { type: 'text/plain;charset=utf-8' })
    const url  = URL.createObjectURL(blob)
    const a    = Object.assign(document.createElement('a'), { href: url, download: 'bootstrap.sh' })
    a.click()
    URL.revokeObjectURL(url)
  })

  // Copy buttons
  function makeCopyBtn(btnId, getValue) {
    container.querySelector(btnId)?.addEventListener('click', function () {
      navigator.clipboard.writeText(getValue()).then(() => {
        const orig = this.textContent
        this.textContent = 'Kopiert!'
        this.disabled = true
        setTimeout(() => { this.textContent = orig; this.disabled = false }, 1500)
      })
    })
  }

  makeCopyBtn('#bg-tl-copy-url', () => container.querySelector('#bg-tl-url').value)
  makeCopyBtn('#bg-tl-copy-cmd', () => container.querySelector('#bg-tl-cmd').textContent)

  // Restart
  container.querySelector('#bg-restart').addEventListener('click', () => {
    generatedScript = ''
    showStep(1)
  })
}
